version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-idp
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_idp_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - idp-network

  idp:
    build: .
    container_name: idp
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/idp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      FINANCE_DATA_BASE_URL: http://host.docker.internal:8082
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - idp-network

volumes:
  postgres_idp_data:

networks:
  idp-network:
    driver: bridge
